root = "."
tmp_dir = "build"

[build]
bin = "./build/docker-home"
cmd = "go build -o ./build/docker-home ./cmd/main.go"
delay = 1000
exclude_dir = ["assets", "data", "build", "vendor", "testdata"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
include_ext = ["go", "tmpl"]

[misc]
clean_on_exit = true

[proxy]
app_port = 8080
enabled = true
proxy_port = 6969
